version: '3.8'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: hamnen_sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./volumes/config:/config
      - ./volumes/tv:/tv
      - ./volumes/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
