version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: hamnen_jenkins
    restart: unless-stopped
    ports:
      - "8121:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

networks:
  default:
    name: hamnen-network
    external: true
