version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: hamnen_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./volumes/data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=hamnen
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/

networks:
  default:
    name: hamnen-network
    external: true
