version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: hamnen_portainer
    restart: unless-stopped
    ports:
      - "9001:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: --http-enabled

volumes:
  portainer_data:

networks:
  default:
    name: hamnen-network
    external: true
