version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: hamnen_homepage
    restart: unless-stopped
    ports:
      - "3004:3000"
    volumes:
      - ./volumes/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=1000
      - PGID=1000

networks:
  default:
    name: hamnen-network
    external: true
