version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: hamnen_plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - VERSION=docker
    volumes:
      - ./volumes/config:/config
      - ./volumes/movies:/movies
      - ./volumes/tv:/tv
