version: '3.8'

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: hamnen_emby
    restart: unless-stopped
    ports:
      - "8097:8096"
    volumes:
      - ./volumes/config:/config
      - ./volumes/movies:/data/movies
      - ./volumes/tv:/data/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
