version: '3.8'

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: hamnen_lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - ./volumes/config:/config
      - ./volumes/music:/music
      - ./volumes/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
