version: '3.8'

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: hamnen_radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ./volumes/config:/config
      - ./volumes/movies:/movies
      - ./volumes/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
