version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: hamnen_traefik
    restart: unless-stopped
    ports:
      - "8084:8080"
      - "8085:80"
      - "8086:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/config:/etc/traefik
      - ./volumes/letsencrypt:/letsencrypt
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

networks:
  default:
    name: hamnen-network
    external: true
