version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: hamnen_openvpn
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./volumes/config:/etc/openvpn

networks:
  default:
    name: hamnen-network
    external: true
