version: '3.8'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: hamnen_prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ./volumes/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
