version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: hamnen_transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
      - ./volumes/watch:/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
