version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: hamnen_loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./volumes/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki_network

  promtail:
    image: grafana/promtail:latest
    container_name: hamnen_promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./volumes/promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki_network
    depends_on:
      - loki

networks:
  loki_network:
    name: hamnen_loki_network
