version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: hamnen_mattermost_db
    restart: unless-stopped
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    networks:
      - mattermost_network

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: hamnen_mattermost
    restart: unless-stopped
    ports:
      - "8065:8065"
    volumes:
      - ./volumes/config:/mattermost/config
      - ./volumes/data:/mattermost/data
      - ./volumes/logs:/mattermost/logs
      - ./volumes/plugins:/mattermost/plugins
      - ./volumes/client-plugins:/mattermost/client/plugins
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
    networks:
      - mattermost_network
    depends_on:
      - postgres

networks:
  mattermost_network:
    name: hamnen_mattermost_network
