version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: hamnen_sonarqube
    restart: unless-stopped
    ports:
      - "9002:9000"
    volumes:
      - ./volumes/data:/opt/sonarqube/data
      - ./volumes/extensions:/opt/sonarqube/extensions
      - ./volumes/logs:/opt/sonarqube/logs
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: hamnen_sonarqube_db
    restart: unless-stopped
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

networks:
  default:
    name: hamnen-network
    external: true
