version: '3.8'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: hamnen_qbittorrent
    restart: unless-stopped
    ports:
      - "8098:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080

networks:
  default:
    name: hamnen-network
    external: true
