version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: hamnen_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

networks:
  default:
    name: hamnen-network
    external: true
