version: '3.8'

services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: hamnen_speedtest_tracker
    restart: unless-stopped
    ports:
      - "8110:80"
    volumes:
      - ./volumes/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
