version: '3.8'

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: hamnen_bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ./volumes/config:/config
      - ./volumes/movies:/movies
      - ./volumes/tv:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
