version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: hamnen_portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data
    command: --http-enabled
