version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: hamnen_portainer
    restart: unless-stopped
    ports:
      - "9001:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/johan/AI/hamnen/apps/portainer/volumes/portainer_data:/data
    command: --http-enabled
