version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: hamnen_nextcloud
    restart: unless-stopped
    ports:
      - "8115:80"
    volumes:
      - ./volumes/html:/var/www/html
      - ./volumes/data:/var/www/html/data
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: hamnen_nextcloud_db
    restart: unless-stopped
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud_root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

networks:
  default:
    name: hamnen-network
    external: true
