version: '3.8'

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: hamnen_tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./volumes/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
