version: '3.8'

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: hamnen_duplicati
    restart: unless-stopped
    ports:
      - "8200:8200"
    volumes:
      - ./volumes/config:/config
      - ./volumes/backups:/backups
      - ./volumes/source:/source
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
