version: '3.8'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hamnen_homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=UTC
    privileged: true
