version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: hamnen_vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    volumes:
      - ./volumes/data:/vault/data
      - ./volumes/logs:/vault/logs
      - ./volumes/config:/vault/config
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id="root"
    networks:
      - vault_network

networks:
  vault_network:
    name: hamnen_vault_network
