version: '3.8'

services:
  esphome:
    image: esphome/esphome:latest
    container_name: hamnen_esphome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=UTC
