version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hamnen_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hamnen
      - MONGO_INITDB_ROOT_PASSWORD=hamnen_password

networks:
  default:
    name: hamnen-network
    external: true
