version: '3.8'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: hamnen_syncthing
    restart: unless-stopped
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - ./volumes/config:/config
      - ./volumes/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

networks:
  default:
    name: hamnen-network
    external: true
