version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: hamnen_grafana
    restart: unless-stopped
    user: "472"
    ports:
      - "3050:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=hamnen
      - GF_INSTALL_PLUGINS=

volumes:
  grafana_data:

networks:
  default:
    name: hamnen-network
    external: true
