version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: hamnen_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/data:/data
    command: redis-server --appendonly yes

networks:
  default:
    name: hamnen-network
    external: true
