version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: hamnen_nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./volumes/data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=273m
    networks:
      - nexus_network

networks:
  nexus_network:
    name: hamnen_nexus_network
